name: ðŸ§ª Tests
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.24", "1.25"]
        os:
          - runner: ubuntu-latest
            name: ubuntu-x86_64
          - runner: ubuntu-24.04-arm
            name: ubuntu-arm64
          - runner: macos-14
            name: macos-arm64
          - runner: macos-14-large
            name: macos-x86_64
      fail-fast: false

    runs-on: ${{ matrix.os.runner }}
    name: test on ${{ matrix.os.name }} with Go ${{ matrix.go-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install tools
        run: make install-tools

      - name: Run tests
        run: make test
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        if: ${{ !contains(matrix.os.name, 'arm64') }}
        with:
          fail_ci_if_error: true
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  test-instrumentation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.24", "1.25"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install tools
        run: make install-tools

      - name: Run tests
        run: make test-instrumentation

  build-sample-apps:
    name: "Build ${{ matrix.app }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ["echo-postgres", "gin-postgres"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Install tools
        run: make install-tools

      - name: Build ${{ matrix.app }} app
        working-directory: ./sample-apps/${{ matrix.app }}
        run: make build
